#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Context Pilot — Dev Loop Runner
# Auto-generated by `context-pilot init-workflow`
#
# Usage:
#   chmod +x dev.sh
#   ./dev.sh "Implement user authentication"
#
# This script runs the full AI-assisted dev loop:
#   1. Sets the current task
#   2. Scans the project for context
#   3. Opens your preferred AI tool
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

TASK="${1:-}"

if [ -z "$TASK" ]; then
  echo "Usage: ./dev.sh \"task description\""
  exit 1
fi

echo "🚀 Context Pilot — Starting dev loop"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Step 1: Set the task
echo "📋 Setting task: $TASK"
npx context-pilot task "$TASK"

# Step 2: Scan the project
echo ""
echo "🔍 Scanning project..."
npx context-pilot scan

# Step 3: Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Ready! Your AI context is prepared."
echo ""
echo "Files created/updated:"
echo "  • CONTEXT.md        — prioritized source files"
echo "  • ARCHITECTURE.md   — system architecture map"
echo "  • AI-TASK.md        — current task"
echo "  • AI-MEMORY.md      — persistent memory"
echo ""
echo "Next: Open your AI tool (Continue.dev, Aider, Cursor)"
echo "      and paste CONTEXT.md or use the Continue config."
