version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: ch_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: coding_platform

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ch_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/coding_platform
      JWT_SECRET_KEY: codehouse-docker-secret-change-in-prod
      FLASK_ENV: production
      FLASK_DEBUG: "False"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ch_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo_data:
